spring.application.name=epic

# MySQL DATABASE ??

# DB Source URL
spring.datasource.url=jdbc:mysql://inu-epic.mysql.database.azure.com:3306/epicsv?serverTimezone=UTC&useSSL=true&requireSSL=false

# DB username
spring.datasource.username=epic

# DB password
spring.datasource.password=Dlehdrb0101@

# JPA ?? ??. ?? ?? ??? ?
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# DB ??? ??. ???? ?? DB ??? ??, ??, ??, ?? ??. ???? ??
spring.jpa.hibernate.ddl-auto=update

# ???? SQL ???
spring.jpa.properties.hibernate.show_sql=true

# hibernate ?? ? ??? SQL? ??? ??
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver