spring.application.name=epic

# DATABASE
# h2 db ?? ??
spring.h2.console.enabled=true
# h2 db ?? ??
spring.h2.console.path=/h2-console
# db ?? ?? ??
spring.datasource.url=jdbc:h2:~/local
spring.datasource.driverClassName=org.h2.Driver
# db ????
spring.datasource.username=sa
# db ????
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update